# Configure tool filters
tool_filters:
  settings:
    allow_write: true
  enabled_tools:
    - ListIndexTool
    - SearchIndexTool
    - CountTool
    - ExplainTool
    - CreateSearchConfigurationTool
    - GetSearchConfigurationTool
    - DeleteSearchConfigurationTool
    - CreateQuerySetTool
    - SampleQuerySetTool
    - GetQuerySetTool
    - DeleteQuerySetTool
  disabled_tools:
    - IndexMappingTool
    - GetShardsTool
    - ClusterHealthTool
    - MsearchTool
